--
-- PostgreSQL database dump
--

\restrict hmXpjhGfk3grBh6CW8uIZK09r7h1fT7eaUalkwpkIGaUV3KMX2YJTP6FxTSgNEl

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: departments_department; Type: TABLE DATA; Schema: public; Owner: drp_user
--

INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (5, 'bessSales', 'BESS Sales', 'amber', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.751948+00', '2026-04-30 09:27:52.993502+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (6, 'design', 'Design', 'indigo', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.767425+00', '2026-04-30 09:27:53.001121+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (7, 'finance', 'Finance', 'emerald', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.769853+00', '2026-04-30 09:27:53.003888+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (8, 'hrDept', 'HR', 'rose', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.772472+00', '2026-04-30 09:27:53.00728+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (10, 'om', 'O & M', 'zinc', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.780681+00', '2026-04-30 09:27:53.019341+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (12, 'project', 'Project', 'rose', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.789347+00', '2026-04-30 09:27:53.030133+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (13, 'rd', 'R & D', 'indigo', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.792711+00', '2026-04-30 09:27:53.034157+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (16, 'support', 'Support', 'amber', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.803344+00', '2026-04-30 09:27:53.051862+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (17, 'webDev', 'Web Dev', 'indigo', '[{"key": "workDone", "label": "Work Done"}, {"key": "workInProgress", "label": "Work in Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challenges", "label": "Challenges Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.808254+00', '2026-04-30 09:27:53.057805+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (20, 'insideSales', 'Inside Sales', 'amber', '[{"key": "totalCalls", "label": "Total Calls"}, {"key": "picked", "label": "Picked"}, {"key": "closed", "label": "Closed"}, {"key": "lost", "label": "Lost"}, {"key": "following", "label": "Following"}, {"key": "invoiceTotal", "label": "Invoice Total (₹)"}, {"key": "dataCalled", "label": "Data Called"}]', '2026-05-08 11:12:57.558871+00', '2026-05-08 11:12:57.558871+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (14, 'rdBess', 'R & D-BESS', 'sky', '[{"key": "task", "label": "Task"}, {"key": "workProgress", "label": "Work Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}, {"key": "challengesFaced", "label": "Challenge Faced / Support Needed"}, {"key": "otherUpdate", "label": "Other Update"}]', '2026-04-30 07:46:25.795306+00', '2026-04-30 09:27:53.039309+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (4, 'procurement', 'Procurement', 'emerald', '[{"key": "enquiries", "label": "Enquiries for Pricing Done"}, {"key": "negotiations", "label": "Comparison & Negotiations"}, {"key": "vendorOnboarding", "label": "Vendor Onboarding / Meeting"}, {"key": "purchaseOrder", "label": "Purchase Order Process"}, {"key": "payment", "label": "Payment Process (NOPA)"}, {"key": "dispatches", "label": "Dispatches Done"}, {"key": "grn", "label": "GRN / Material Received"}, {"key": "remarks", "label": "Remarks"}]', '2026-04-29 12:27:31.943476+00', '2026-05-01 06:16:05.079958+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (1, 'sales', 'Sales', 'rose', '[{"key": "meeting", "label": "Meeting"}, {"key": "revenue", "label": "Revenue"}, {"key": "newCustomerOnboard", "label": "New Customer Onboard"}]', '2026-04-29 12:27:31.906236+00', '2026-05-01 06:20:53.172304+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (3, 'marketing', 'Marketing', 'indigo', '[{"key": "videoEditing", "label": "Video Making / Editing"}, {"key": "creatives", "label": "Creatives"}, {"key": "contentWriting", "label": "Content Writing"}, {"key": "seo", "label": "SEO"}, {"key": "websiteManagement", "label": "Website Management"}, {"key": "reporting", "label": "Reporting"}, {"key": "otherWorks", "label": "Other Works"}, {"key": "brochurePptPdfEdits", "label": "Brochure / PPT / PDF Edits"}]', '2026-04-29 12:27:31.938566+00', '2026-05-01 06:20:53.204679+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (9, 'logistics', 'Logistics', 'sky', '[{"key": "warehouseCoordination", "label": "Warehouse Coordination"}, {"key": "truckTransportationCoordination", "label": "Truck Transportation Coordination"}, {"key": "courierDispatch", "label": "Courier Dispatch"}, {"key": "shipmentTracking", "label": "Shipment Tracking"}, {"key": "freightSharingDetails", "label": "Freight Sharing Details"}, {"key": "flasherDataUpload", "label": "Flasher Data Upload"}, {"key": "stockIn", "label": "Stock In"}, {"key": "stockOut", "label": "Stock Out"}, {"key": "portalOperations", "label": "Portal Operations"}, {"key": "courierIssueResolution", "label": "Courier Issue Resolution"}, {"key": "inventoryManagement", "label": "Inventory Management"}, {"key": "otherOperationalWork", "label": "Other Operational Work"}]', '2026-04-30 07:46:25.775297+00', '2026-04-30 10:23:33.376326+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (11, 'production', 'Production', 'amber', '[{"key": "timeSlot1", "label": "Time Slot 1 (10:00 – 13:30)"}, {"key": "timeSlot2", "label": "Time Slot 2 (14:00 – 18:15)"}, {"key": "todaysOutcome", "label": "Todays Outcome"}, {"key": "pendingWork", "label": "Pending Work"}, {"key": "planForTomorrow", "label": "Plan for Tomorrow"}, {"key": "unitsProducedThisWeek", "label": "No. of Units Produced During the Week"}]', '2026-04-30 07:46:25.786485+00', '2026-04-30 09:27:53.026187+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (15, 'service', 'Service', 'emerald', '[{"key": "solarInstallationSiteVisit", "label": "Solar Installation Site Visit"}, {"key": "inverterComplaintSiteVisit", "label": "Inverter Complaint Site Visit"}, {"key": "inverterComplaintTeleVideo", "label": "Inverter Complaint (Tele / Video — Open / Resolved)"}, {"key": "inverterPartReplacement", "label": "Inverter Part Replacement"}, {"key": "otherWork", "label": "Other Work"}]', '2026-04-30 07:46:25.800496+00', '2026-04-30 09:27:53.047599+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (22, 'salesService', 'Sales Service', 'sky', '[{"key": "umangComplaints", "label": "Umang Complaints"}, {"key": "kusumDocsSubmitted", "label": "Kusum Docs Submitted"}, {"key": "loanDocsSubmitted", "label": "Loan Docs Submitted"}, {"key": "salesCallingDone", "label": "Sales Calling Done"}, {"key": "otherWork", "label": "Other Work"}]', '2026-05-14 14:57:22.566707+00', '2026-05-14 14:57:22.566707+00');
INSERT INTO public.departments_department (id, slug, name, color, report_fields, created_at, updated_at) VALUES (23, 'productionMgmt', 'Production Management', 'indigo', '[{"key": "task", "label": "Task"}, {"key": "workProgress", "label": "Work Progress"}, {"key": "upcomingPriorities", "label": "Upcoming Priorities"}]', '2026-05-14 15:43:56.322146+00', '2026-05-14 15:43:56.322146+00');


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: drp_user
--

INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (140, 'pbkdf2_sha256$600000$m-9843V_pOk3tWbs4Fqhuw$xkyYGSJDYMQa1F6DLjHRiQGvCGot0V1+RDzKzT9IrCU=', NULL, true, 'tarini', 'Tarini', 'Aggrawal', 'tarini@ornatesolar.com', true, true, '2026-05-08 11:12:57.558871+00', '', 'hr', 'CEO', NULL, NULL, '', '');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (36, 'pbkdf2_sha256$870000$6Iq92rf8FRkkI55aMlGU5F$+WN3KM7uF3AqPD5XxvBbJ764uHaV5fQJZ9QqJMl3oHo=', NULL, false, 'dhathresh', 'Dhathresh', 'Patnam', 'dhathresh@ornatesolar.com', false, true, '2026-04-30 07:46:25.994908+00', '', 'employee', '', 5, '2025-01-14', 'Ornate', 'Fateh Brar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (51, 'pbkdf2_sha256$870000$UZb1VoTRw1Oxds8fYF9c1y$GqFl1kNULFWdQLj4Wc9dqXRqgQQowNGFKoyrM7Zb2rA=', NULL, true, 'smita', 'Smita', 'Sharma', 'smita@ornatesolar.com', true, true, '2026-04-30 07:46:28.696254+00', '', 'hr', '', 8, '2023-07-17', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (37, 'pbkdf2_sha256$870000$2Ijm5fCRAM3HosYyOEU70b$qoR3m/Q9Jc+f/ljKQSZizkzV0cekb8wstWvjWsV2cP4=', NULL, false, 'kedar', 'Kedar', 'Balasubramanian', 'kedar@ornatesolar.com', false, true, '2026-04-30 07:46:26.17246+00', '', 'employee', '', 5, '2025-10-27', 'Ornate', 'Fateh Brar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (38, 'pbkdf2_sha256$870000$zjBjG60dyjcpiXObmk07HA$3YSOSmyDkTT1ChdNaQMt7Qr4tm5LuifciYsfKifT1OU=', NULL, false, 'visal', 'Visal', 'Pundir', 'visal@ornatesolar.com', false, true, '2026-04-30 07:46:26.351458+00', '', 'employee', '', 5, '2026-01-01', 'Ornate', 'Fateh Brar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (35, 'pbkdf2_sha256$870000$hvMNCHk4MbekLDXyuSspxM$FAVjG4PBJFZ6vQhio6tSHoUsdOEQOjs+154yFlGfMpk=', NULL, false, 'fateh', 'Fateh', 'Brar', 'fateh@ornatesolar.com', true, true, '2026-04-30 07:46:25.810536+00', '', 'employee', '', 5, '2024-01-01', 'Ornate', 'Aditya Goel');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (39, 'pbkdf2_sha256$870000$7brJTVjfKIpqguYoZ2shoo$4WMQwpTSB8ZVu3hzOpk0QLvjmfMV14Uqc8xSqfzAtgQ=', NULL, false, 'parvez', 'Parvez', 'Yusuf', 'parvez@ornatesolar.com', false, true, '2026-04-30 07:46:26.534151+00', '', 'employee', '', 6, '2024-10-07', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (40, 'pbkdf2_sha256$870000$1wu4eSapDWQZBScN0SVrEJ$r+gZxzD6p71JducQGOXwQvxWWz9KBojbEGFVCpVzpw4=', NULL, false, 'banti', 'Banti', '', 'banti@ornatesolar.com', false, true, '2026-04-30 07:46:26.708399+00', '', 'employee', '', 6, '2025-11-10', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (93, 'pbkdf2_sha256$870000$HlZ7elALpQS9XP75H9xeS9$tOeyjgYR+lc3D82hKixQ3JrB5AHnpt8ZNdKUmn4tYvA=', NULL, false, 'seema', 'Seema', 'Roy', 'seema@ornatesolar.com', false, true, '2026-04-30 07:46:37.096588+00', '', 'employee', '', 20, '2021-02-01', 'Ornate', 'Geetu Bhatija');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (41, 'pbkdf2_sha256$870000$vGDsJtigxDpps8UnAxisOq$+RqSGopsKHcKGseDNp6+8d6L10fR8vXrJWNfwkdnTA0=', NULL, false, 'rahul', 'Rahul', 'Kumar', 'rahul@ornatesolar.com', false, true, '2026-04-30 07:46:26.886427+00', '', 'employee', '', 6, '2026-01-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (95, 'pbkdf2_sha256$870000$dtgAaePvgBgy0CUSG6VYan$vmGZSMOo6UG9QD9vmq/uoKIudDbTNqgCm1iIPrHBPt0=', NULL, false, 'monika', 'Monika', 'Bhardwaj', 'monika@ornatesolar.com', false, true, '2026-04-30 07:46:37.489856+00', '', 'employee', '', 20, '2023-04-01', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (42, 'pbkdf2_sha256$870000$3PEOiDCt6yDzFyMgFCp6WL$4FaS4foXqw6EfC/sMVyFSeocvHRZAPKeE3vM3dja4Go=', NULL, false, 'shivangi', 'Shivangi', 'Singh', 'shivangi@ornatesolar.com', false, true, '2026-04-30 07:46:27.080466+00', '', 'employee', '', 7, '2016-08-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (97, 'pbkdf2_sha256$870000$j2Ywc6d8VnipXebFzLMpS6$vhfLbQvoM7Lbd5nWFYNjq82ooNTVguDaM2oI993xkN0=', NULL, false, 'rakhi', 'Rakhi', 'Sharma', 'rakhi@ornatesolar.com', false, true, '2026-04-30 07:46:37.885812+00', '', 'employee', '', 20, '2024-01-29', 'Ornate', 'Geetu Bhatija');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (43, 'pbkdf2_sha256$870000$cAa40p9hffqt3FOL7ZX8WV$+qrXB20fwXRVlvvKFEr1hI8a9KHgDVrVs33SjGgZSPU=', NULL, false, 'neeraj', 'Neeraj', 'Priyadarshi', 'neeraj@ornatesolar.com', false, true, '2026-04-30 07:46:27.256942+00', '', 'employee', '', 7, '2021-08-09', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (103, 'pbkdf2_sha256$870000$w6w9WIf9XJVB91UdUHuNIH$MuebFjmewTUqd6TM3Flc479pcMUUHTAzkLjY6MUmOVE=', NULL, false, 'ranjana', 'Ranjana', '', 'ranjana@ornatesolar.com', false, true, '2026-04-30 07:46:39.013388+00', '', 'employee', '', 20, '2022-09-12', 'Ornate', 'Geetu Bhatija');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (44, 'pbkdf2_sha256$870000$uJtpQC1U2oLjlEmUAKtCsc$Brep4RLoXTPw3sU4A8fK183JxjLUCGih1XzSwB14YUI=', NULL, false, 'bittu', 'Bittu', 'Kumar', 'bittu@ornatesolar.com', false, true, '2026-04-30 07:46:27.442531+00', '', 'employee', '', 7, '2022-08-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (139, 'pbkdf2_sha256$870000$xNk2Ctw3RPDEx7XHQLLOc5$JP/Ww8y8IJPpEWc98icxgg2zInB9X7o+RPu2UBhlOL8=', NULL, false, 'vivek', 'Vivek', 'Sharma', 'vivek@ornatesolar.com', false, true, '2026-04-30 09:27:53.521007+00', '', 'employee', '', 23, '2025-12-09', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (45, 'pbkdf2_sha256$870000$8MkLwvGj0W2wJ5ErTDGCow$tJx+f1uZapvxaQFfBZem6CTtw3gM2LwrxFbM6yW85Ts=', NULL, false, 'pradeepa', 'Pradeepa', '', 'pradeepa@ornatesolar.com', false, true, '2026-04-30 07:46:27.623535+00', '', 'employee', '', 7, '2023-08-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (46, 'pbkdf2_sha256$870000$HNVBcqY5XPtML5tUL0Iy2d$txF5agNhRJiS2jclCbmyyIzzGi0+8w5EbR6M3cF6eu8=', NULL, false, 's', 'S', 'Monika Selvam P', 's@ornatesolar.com', false, true, '2026-04-30 07:46:27.797715+00', '', 'employee', '', 7, '2023-08-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (47, 'pbkdf2_sha256$870000$t1Q3tWUAVWDHl9cPbPWxAF$SMZbo+TrWfHlrrx558pwDOJjRgOezHfuoDgRa1JO4Ww=', NULL, false, 'ekta', 'Ekta', '', 'ekta@ornatesolar.com', false, true, '2026-04-30 07:46:27.96797+00', '', 'employee', '', 7, '2025-03-18', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (137, 'pbkdf2_sha256$870000$O2D7yLsiU0nx43aep1kGSJ$DtgAQT+Wt5/wsnTfVT3SsPoS8kdT+dycWu6jh849E4g=', NULL, false, 'mohit', 'Mohit', 'Kashyap', 'mohit@ornatesolar.com', false, true, '2026-04-30 09:27:53.079853+00', '', 'employee', '', 7, '2025-06-11', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (49, 'pbkdf2_sha256$870000$m2NaJdzuG5QH46Pr5RdvwY$tIyYHO9Srb8Rjmewmj3BISfAGbKFvbN1S/Qezmir4es=', NULL, false, 'ridhi', 'Ridhi', 'Jain', 'ridhi@ornatesolar.com', false, true, '2026-04-30 07:46:28.324956+00', '', 'employee', '', 7, '2025-08-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (50, 'pbkdf2_sha256$870000$eP7QgknxDL482OrnWKtBmB$Z9A1wK4HAZp+3wQ5UhVD0ugqY9CKXVccNbutVOObnJ8=', NULL, false, 'saif', 'Saif', 'Ur Rehman', 'saif@ornatesolar.com', false, true, '2026-04-30 07:46:28.51023+00', '', 'employee', '', 7, '2025-09-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (52, 'pbkdf2_sha256$870000$K6VZ9J6iKzVH6hEy4GVtBs$8xCa+X1khjyOMPdE+NdRtCjET8UzZQ/BG5fYrJur548=', NULL, false, 'madhu', 'Madhu', 'Sharma', 'madhu@ornatesolar.com', false, true, '2026-04-30 07:46:28.874353+00', '', 'employee', '', 9, '2025-06-25', 'Ornate', '');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (53, 'pbkdf2_sha256$870000$oRA3KIKxHy0T9YMerfcTsu$ciIricoHFife/7ACCgoMLrvegfy45Lc9Q+ExH2G8Gt0=', NULL, false, 'divyansh', 'Divyansh', '', 'divyansh@ornatesolar.com', false, true, '2026-04-30 07:46:29.063157+00', '', 'employee', '', 9, '2025-09-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (55, 'pbkdf2_sha256$870000$unmbGhKtGu3nOs1jbEBfeo$sMSUMNqUAxblymbmbumpdN8e8Rz77YIWagZrfWYZ7ks=', NULL, false, 'lalit', 'Lalit', 'Jaiswal', 'lalit@ornatesolar.com', false, true, '2026-04-30 07:46:29.448171+00', '', 'employee', '', 9, '2025-03-03', 'Rama', 'Divyansh');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (56, 'pbkdf2_sha256$870000$Xj1XL41oXrcPeptzKTcEYO$KmV+LDzMk5YAAnLxogDmO9IwZqFnIIxEkGlwUouSmck=', NULL, false, 'satyam', 'Satyam', '', 'satyam@ornatesolar.com', false, true, '2026-04-30 07:46:29.669802+00', '', 'employee', '', 9, '2025-06-16', 'Rama', 'Divyansh');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (57, 'pbkdf2_sha256$870000$kQNujikIKDurOf5FrQtKsl$FwQuKx6tsrdmhfA4LQGa3vPH7gzeYFyyc2V1gK4lkT4=', NULL, false, 'rohit', 'Rohit', 'Kumar', 'rohit@ornatesolar.com', false, true, '2026-04-30 07:46:29.868271+00', '', 'employee', '', 3, '2019-07-01', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (58, 'pbkdf2_sha256$870000$H7Q8fmDBn19WH5FRCwdjCM$MZ4GDwU7gjgU4Zdc0qBVgTQ53ZdrJRysdAM8qZ47FN8=', NULL, false, 'pinky', 'Pinky', 'Bosh', 'pinky@ornatesolar.com', false, true, '2026-04-30 07:46:30.042551+00', '', 'employee', '', 3, '2019-04-23', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (138, 'pbkdf2_sha256$870000$QV1uJ6nT2QqCxJlurb1DIb$SGVeXLXHcLIgB8XTYK8m1wzy2a1Ga1a3IdHulXSmlr0=', NULL, false, 'anjali', 'Anjali', '', 'anjali@ornatesolar.com', false, true, '2026-04-30 09:27:53.284013+00', '', 'employee', '', 3, '2023-05-29', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (60, 'pbkdf2_sha256$870000$7B1cG1Q4D8ub5dRLva7uTJ$kO2gPKAPLXlvuWFhD23nc2KTI2hhMlGMwVVsPRmBj2o=', NULL, false, 'srishti', 'Srishti', 'Vadera', 'srishti@ornatesolar.com', false, true, '2026-04-30 07:46:30.4135+00', '', 'employee', '', 3, '2025-03-24', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (61, 'pbkdf2_sha256$870000$jpy9dB0Qz3lK1wwGqI3FqS$kHUdUFIGzQsfQKvfRuZhdPS6tmGF1DxbqHLSy0+yys4=', NULL, false, 'saba', 'Saba', '', 'saba@ornatesolar.com', false, true, '2026-04-30 07:46:30.631782+00', '', 'employee', '', 10, '2025-12-01', 'Ornate', 'Rahul Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (62, 'pbkdf2_sha256$870000$AB58jgZkTANXESYp81AaqL$sFbsNRkeSMYIezfhsExk1qmO7a2atvkhiYUKe6ZLfz8=', NULL, false, 'rahul2', 'Rahul', 'Sharma', 'rahul2@ornatesolar.com', false, true, '2026-04-30 07:46:30.819114+00', '', 'employee', '', 4, '2024-08-20', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (63, 'pbkdf2_sha256$870000$VoxPDWghX9mRsrhZfl5TQr$NFiK2dTT9PFa5lP/brkit9bW6IXljCvYTiHbRacLe+U=', NULL, false, 'abhishek', 'Abhishek', 'Jadon', 'abhishek@ornatesolar.com', false, true, '2026-04-30 07:46:30.994157+00', '', 'employee', '', 4, '2025-06-24', 'Ornate', 'Rahul Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (64, 'pbkdf2_sha256$870000$gVSS3E8r1GxcGLWtEz3ZyF$wzTd5FfORKXY/17mTDCUMtOaa+9rrDpP/KMl3XwLeP8=', NULL, false, 'atishay', 'Atishay', 'Jain', 'atishay@ornatesolar.com', false, true, '2026-04-30 07:46:31.166079+00', '', 'employee', '', 4, '2026-01-01', 'Ornate', 'Anisha Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (65, 'pbkdf2_sha256$870000$gzLxQSP6QdicG3b5MDz3pF$rwh8CJIEIUzqJL+pCzuHF8NVuvfR1azHpj6nwEbMF5k=', NULL, false, 'rajvir', 'Rajvir', 'Singh', 'rajvir@ornatesolar.com', false, true, '2026-04-30 07:46:31.342994+00', '', 'employee', '', 11, '2024-02-28', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (66, 'pbkdf2_sha256$870000$shwwjW9nwj6COqoMM3Q82T$i8dKvw3BFx4zCOMI5RmjAw7rIcDQPYy/oaiH2+NsVYk=', NULL, false, 'amir', 'Amir', 'Khan', 'amir@ornatesolar.com', false, true, '2026-04-30 07:46:31.511223+00', '', 'employee', '', 11, '2025-03-18', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (68, 'pbkdf2_sha256$870000$1tXWSqnsi4pQ7LjqgC9tOh$WVE3XvYm4FsY+gjqpFezsFYK6cpHE4weI9Q6haaVh2s=', NULL, false, 'sameer', 'Sameer', 'Khan', 'sameer@ornatesolar.com', false, true, '2026-04-30 07:46:31.876106+00', '', 'employee', '', 11, '2025-09-01', 'Rama', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (69, 'pbkdf2_sha256$870000$SXwvV7kCGrjX37JPh0NUWB$Wr/0ZQ0fPOt2GcKgBv/jYfXCo7nVJ2pvweUCNw7LgRU=', NULL, false, 'anil', 'Anil', 'Pathak', 'anil@ornatesolar.com', false, true, '2026-04-30 07:46:32.068326+00', '', 'employee', '', 12, '2025-07-15', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (70, 'pbkdf2_sha256$870000$ZqFuOLzDDbe0pYTXlMXP0H$r9m8u7uBfxZEkWY66/XUiDXGk9E3YvNR1wYmhwIDEQw=', NULL, false, 'vijay', 'Vijay', 'kumar pal', 'vijay@ornatesolar.com', false, true, '2026-04-30 07:46:32.256262+00', '', 'employee', '', 12, '2026-01-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (71, 'pbkdf2_sha256$870000$zy7GOtIWNUmx6c37tIgp15$HYaOqsuDqRHh+kEVGL3Qzv6PLtLBT33w5CWYb5j4Z3Y=', NULL, false, 'arup', 'Arup', 'Hazra', 'arup@ornatesolar.com', false, true, '2026-04-30 07:46:32.447895+00', '', 'employee', '', 12, '2026-02-21', 'Ornate', 'Aditya Goel');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (72, 'pbkdf2_sha256$870000$7oSwv4YslL6CWttb6OycCV$pzqVKBq6PHZHV2b6PWmtzrHbeiU4dFZ0Ogakf32/WoM=', NULL, false, 'shivangi2', 'Shivangi', 'Pandey', 'shivangi2@ornatesolar.com', false, true, '2026-04-30 07:46:32.627247+00', '', 'employee', '', 12, '2026-02-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (73, 'pbkdf2_sha256$870000$drXgCYizpCwXFSdKNeVV8t$TP7uK7zsMFrNq4tNrsLO/ZnZkePMJkpJoe8jnvidXDY=', NULL, false, 'arghyadip', 'ARGHYADIP', 'BHATTACHARJEE', 'arghyadip@ornatesolar.com', false, true, '2026-04-30 07:46:32.829392+00', '', 'employee', '', 13, '2022-11-01', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (74, 'pbkdf2_sha256$870000$qiwt4o6IUxT8tEI24GSXt4$L4h3cJ9v2/U+s3MZvlBLDF727GwZqpkg9fmV8eeZoCM=', NULL, false, 'pravesh', 'Pravesh', 'Kumar', 'pravesh@ornatesolar.com', false, true, '2026-04-30 07:46:33.022587+00', '', 'employee', '', 13, '2023-04-01', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (75, 'pbkdf2_sha256$870000$K4tGMM6seRnReVUYvxPUhu$2DGjtXg1V7mO260s7VlUN0j/gQAZLUm3gkuCtNAsi7Y=', NULL, false, 'krishna', 'Krishna', 'Gullapalli', 'krishna@ornatesolar.com', false, true, '2026-04-30 07:46:33.217857+00', '', 'employee', '', 13, '2023-07-01', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (76, 'pbkdf2_sha256$870000$8fMIXx1XessLbBeLwrb6cz$f4lO7ni0GE4l4B3MFxkwVPSeYBy+2Z9kKMr7iDwxjD8=', NULL, false, 'arindam', 'Arindam', 'Debnath', 'arindam@ornatesolar.com', false, true, '2026-04-30 07:46:33.405639+00', '', 'employee', '', 13, '2023-08-21', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (77, 'pbkdf2_sha256$870000$DPmJPg1YA6QP3JZcuK8LQs$kuNWBdV0TjLNIszKYYeCRZ49HLro68HPtM5+VMr5Sp4=', NULL, false, 'ankit', 'Ankit', 'Kumar Singh', 'ankit@ornatesolar.com', false, true, '2026-04-30 07:46:33.590689+00', '', 'employee', '', 13, '2022-05-09', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (78, 'pbkdf2_sha256$870000$xLUyZH2hcagoUH8dXSnBKU$dnSjF64/lvPSG8WgjWIiHIzVB0iELv1l40WQSXwVTqo=', NULL, false, 'ritika', 'Ritika', 'Agarwal', 'ritika@ornatesolar.com', false, true, '2026-04-30 07:46:33.774393+00', '', 'employee', '', 13, '2024-04-08', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (79, 'pbkdf2_sha256$870000$V5DIP6NcMGYJhKHkmAUNnT$elwkaLGAD19sRNXP+9t0E3UVZ1B7n+vWDVywXZZlGO0=', NULL, false, 'akash', 'Akash', 'Yadav', 'akash@ornatesolar.com', false, true, '2026-04-30 07:46:33.956837+00', '', 'employee', '', 13, '2024-08-01', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (80, 'pbkdf2_sha256$870000$MB90TbxGloZHSZMf0OML4N$O5cjdDTiu0DNRhjN10cHkvNxXEW78PJ65Y9XIhq/R2U=', NULL, false, 'gaurav', 'Gaurav', 'Kumar', 'gaurav@ornatesolar.com', false, true, '2026-04-30 07:46:34.13749+00', '', 'employee', '', 13, '2024-09-16', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (81, 'pbkdf2_sha256$870000$jFKtGq1SmCqqGNu7ZhVOMl$KKr3df5lC6Px6uVGvdOmB7gZ7qmxJWWpvSqjGf/z0Jw=', NULL, false, 'kanchan', 'Kanchan', '', 'kanchan@ornatesolar.com', false, true, '2026-04-30 07:46:34.324515+00', '', 'employee', '', 13, '2024-10-01', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (82, 'pbkdf2_sha256$870000$vnIesarUmE9cTOMGYZ7Ne2$GDh0GpyWenmXxIM/fNb2vcdtdTzBHRJ5D92SC9+Am7k=', NULL, false, 'akankshi', 'Akankshi', 'Trivedi', 'akankshi@ornatesolar.com', false, true, '2026-04-30 07:46:34.508572+00', '', 'employee', '', 13, '2025-02-03', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (83, 'pbkdf2_sha256$870000$GgdWqJhDFDe83CyYIUNJLx$ivE9T8NTN9OUu0KscwcmbwHqH9IW1WoOVSe7TWR/MmM=', NULL, false, 'tamanna', 'Tamanna', '', 'tamanna@ornatesolar.com', false, true, '2026-04-30 07:46:34.699847+00', '', 'employee', '', 13, '2025-08-18', 'Orante', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (84, 'pbkdf2_sha256$870000$UDL8KpQHdr7qAvIkr8bIlb$R/Qa7DfuWxLnOGEXJhBQGxCRamzdMCP72sRgTOl6ttc=', NULL, false, 'aditya', 'Aditya', 'Agrahari', 'aditya@ornatesolar.com', false, true, '2026-04-30 07:46:34.881479+00', '', 'employee', '', 13, '2025-01-06', 'Ornate', 'Bidyut Bhatacharya');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (85, 'pbkdf2_sha256$870000$K4A7sPWOXcrHwdwt3Gv6NC$2WX+E+HxIMR6a8kK7x5sBIy0Il6ciWxFdj/6bxexMxE=', NULL, false, 'aayush', 'Aayush', 'Sharma', 'aayush@ornatesolar.com', false, true, '2026-04-30 07:46:35.064581+00', '', 'employee', '', 14, '2021-11-01', 'Ornate', 'Arvind Jain');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (86, 'pbkdf2_sha256$870000$3DKzratvN57diHchIrIoTg$pdvopAgRMOGntFJLImvAYfo0N/lgrC/WmcE+zMAQ76U=', NULL, false, 'kashyap', 'Kashyap', 'Masiwal', 'kashyap@ornatesolar.com', false, true, '2026-04-30 07:46:35.245967+00', '', 'employee', '', 14, '2024-08-20', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (87, 'pbkdf2_sha256$870000$1HcDoUWbbmw1VXHDrsO9K7$yJQUsKDlAejpDXVcVjRCso0feEl1dBrU0LWmaVsu2Ug=', NULL, false, 'aman', 'Aman', 'Khan', 'aman@ornatesolar.com', false, true, '2026-04-30 07:46:35.470298+00', '', 'employee', '', 14, '2025-07-01', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (88, 'pbkdf2_sha256$870000$0mQB94cckN7brPch0wz2IL$AlEnLTf4c48M5lFaU81Mvvv5fhotTFPh2Lru5t92DN4=', NULL, false, 'dharmendra', 'Dharmendra', 'Yadav', 'dharmendra@ornatesolar.com', false, true, '2026-04-30 07:46:35.740818+00', '', 'employee', '', 14, '2025-08-01', 'Ornate', 'Aayush Sharma');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (89, 'pbkdf2_sha256$870000$fzBJ5qqZ7tXxXCPf2payv9$6/ybqcT4GQNYk9wuU+XZvLOAT+F5JycLHIClbIGlGY4=', NULL, false, 'geetu', 'Geetu', 'Bhateja', 'geetu@ornatesolar.com', false, true, '2026-04-30 07:46:36.111139+00', '', 'employee', '', 1, '2017-06-01', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (90, 'pbkdf2_sha256$870000$6UBOLULsrCGVCksrbayxSs$HJviTGmzGcZtunPLITqyBNWrFUs8GNtS2qhw6JHUauQ=', NULL, false, 'bijoy', 'Bijoy', '', 'bijoy@ornatesolar.com', false, true, '2026-04-30 07:46:36.420062+00', '', 'employee', '', 1, '2018-07-10', 'Ornate', 'Aditya Goel');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (110, 'pbkdf2_sha256$870000$LuXxyVuv0Czs2Q5IPteAh8$awvgcj1oNtTw2vbzVWzAUsl+ThjnkUBBlC5rV5EPVsA=', NULL, false, 'v', 'V', 'Jeevendra', 'v@ornatesolar.com', false, true, '2026-04-30 07:46:40.270532+00', '', 'employee', '', 15, '2024-11-06', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (92, 'pbkdf2_sha256$870000$48I2gKleYNdhKceaCC2m73$nK9ZKjAQOvB8mo58FdOqBjcO9SDRQnfoIKWTcQJqcu8=', NULL, false, 'ashish', 'Ashish', 'Parcha', 'ashish@ornatesolar.com', false, true, '2026-04-30 07:46:36.844626+00', '', 'employee', '', 1, '2020-10-26', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (94, 'pbkdf2_sha256$870000$p5IX37rEToZsnZVnVc23XH$m2uiJNWxzSzSaYfV+Lrm1oKIn4ZycHFtMoKyxJzwszE=', NULL, false, 'gurinder', 'Gurinder', 'pal', 'gurinder@ornatesolar.com', false, true, '2026-04-30 07:46:37.302392+00', '', 'employee', '', 1, '2022-08-16', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (96, 'pbkdf2_sha256$870000$SVx3zPGMzs27BK50Q85qgZ$oCf2Qc7Pk4yvVcS8zijMiqAXFDNIbv3xLM7Vvz94rwM=', NULL, false, 'karan', 'Karan', 'Hitesh Chothani', 'karan@ornatesolar.com', false, true, '2026-04-30 07:46:37.698829+00', '', 'employee', '', 1, '2023-11-27', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (98, 'pbkdf2_sha256$870000$hp5OM3Qknwqr9dmrAeOSbn$6x/3eFQEvnj71pdc8z6UFQ+aOY8JZoCecCSDlOYybSM=', NULL, false, 'abhimanyu', 'Abhimanyu', 'Kaushik', 'abhimanyu@ornatesolar.com', false, true, '2026-04-30 07:46:38.085846+00', '', 'employee', '', 1, '2024-04-01', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (99, 'pbkdf2_sha256$870000$pipMIDAj8xJ9n6S6Jp3yBK$JPa99CcS276GCORutOH6jUznQKX22Rrwbzbgd9cFM88=', NULL, false, 'anil2', 'Anil', 'Kumar', 'anil2@ornatesolar.com', false, true, '2026-04-30 07:46:38.286991+00', '', 'employee', '', 1, '2024-09-26', 'Ornate', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (100, 'pbkdf2_sha256$870000$FeJWjx6vzBKAQzMQyeK9mA$KSBSSUHapf1Yh03IlNcI7EL9ut2L8C+YwWI3ai7cTfk=', NULL, false, 'sanjay', 'Sanjay', 'Shah', 'sanjay@ornatesolar.com', false, true, '2026-04-30 07:46:38.468961+00', '', 'employee', '', 1, '2024-10-01', 'Ornate', 'Aditya Goel');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (102, 'pbkdf2_sha256$870000$SvmZtFEpRX59HxZxxcpPcW$XdeHd1RShjsBo8bYeAsGopMBVrAQ3TQ4LECSLJ0F4Ac=', NULL, false, 'justina', 'Justina', 'Indwar', 'justina@ornatesolar.com', false, true, '2026-04-30 07:46:38.823058+00', '', 'employee', '', 1, '2021-03-04', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (104, 'pbkdf2_sha256$870000$G1kDhhDKAXwntCl5UhY7qr$9nLiSz1xm5neix3LKLC7Nwwzsa3+jgdLsg65UgnImi0=', NULL, false, 'nitika', 'Nitika', '', 'nitika@ornatesolar.com', false, true, '2026-04-30 07:46:39.202234+00', '', 'employee', '', 1, '2025-08-04', 'Ornate', 'Geetu Bhatija');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (105, 'pbkdf2_sha256$870000$46pDM0LIGpINvOJnPHIV0o$s6HHntoF4Z0lRA1Uc50FxlGttgFDQ/d+ZZ4Iru+x6Sg=', NULL, false, 'vivek2', 'Vivek', 'Kumar', 'vivek2@ornatesolar.com', false, true, '2026-04-30 07:46:39.372908+00', '', 'employee', '', 1, '2026-01-29', 'Ornate', 'Sanjay Shah');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (106, 'pbkdf2_sha256$870000$uXDoVjYDmBXZa9s6S7CCul$Rs5CEevsQat3dYxdMYR6vqdVJkPPf7RANOB6B2iTZmI=', NULL, false, 'mohit2', 'Mohit', 'Bhandari', 'mohit2@ornatesolar.com', false, true, '2026-04-30 07:46:39.550431+00', '', 'employee', '', 1, '2025-07-07', 'Rama', 'Bijoy George');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (108, 'pbkdf2_sha256$870000$5yHJGVKAbHFVswM1aFNGZj$iDEQHO/V2cycBROGr1qJsCBp57588IZhw5q4j7uj3XA=', NULL, false, 'navneet', 'Navneet', 'Shukla', 'navneet@ornatesolar.com', false, true, '2026-04-30 07:46:39.908169+00', '', 'employee', '', 1, '2026-01-21', 'Rama', 'Sanjay Shah');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (109, 'pbkdf2_sha256$870000$c5UrNsiOvYahHEERXINPLT$Cob7DmCSbO8fO6o4yeK5emetbf14I2QiioDXI08UZ8o=', NULL, false, 'rohit2', 'Rohit', 'maurya', 'rohit2@ornatesolar.com', false, true, '2026-04-30 07:46:40.095322+00', '', 'employee', '', 15, '2023-02-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (111, 'pbkdf2_sha256$870000$4mDtMEmfjXZzl8MYTGSHO4$VqSd3lRltWvQJRnHbZ5yiOKeeuLSN0+kOQ2e8FSfd00=', NULL, false, 'tosif', 'Tosif', 'Ahamed', 'tosif@ornatesolar.com', false, true, '2026-04-30 07:46:40.449579+00', '', 'employee', '', 15, '2025-08-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (112, 'pbkdf2_sha256$870000$kYADIr4OZgAfJHSkV7HECP$K+e+oRj61if4WfXbArKcM8oRCXoOK4C+OIDs/3sdb1w=', NULL, false, 'tarun', 'Tarun', 'Kumar V', 'tarun@ornatesolar.com', false, true, '2026-04-30 07:46:40.62503+00', '', 'employee', '', 15, '2025-09-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (113, 'pbkdf2_sha256$870000$V82FYHYNcPOHAxNIg6LlfK$hAZOeSyWJDaI5n+XPeHDtCplG/S+fCh/xdMhdcShuMw=', NULL, false, 'manoj2', 'Manoj', 'Kumar Yadav', 'manoj2@ornatesolar.com', false, true, '2026-04-30 07:46:40.800553+00', '', 'employee', '', 15, '2026-01-01', 'Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (125, 'pbkdf2_sha256$870000$kyoVZW8CntbEtL4xc8axcx$hiIwQX9kYIwOiOKgeyzHYMFtg5h/NJSMjPZ/ihudNFs=', NULL, false, 'neelam', 'Neelam', 'Gupta', 'neelam@ornatesolar.com', false, true, '2026-04-30 07:46:42.896078+00', '', 'employee', '', 16, NULL, 'Ware', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (126, 'pbkdf2_sha256$870000$C7ZrXzu5OEqsbuWFAIyFIm$ZEuk+HgVPN88HAIruhEnPbn0ivZTg18FIDMLsFWLc6U=', NULL, false, 'bunty', 'Bunty', '', 'bunty@ornatesolar.com', false, true, '2026-04-30 07:46:43.073645+00', '', 'employee', '', 16, '2022-02-01', 'Ware', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (127, 'pbkdf2_sha256$870000$aE8GSGIXjnSnv3KQ2DTNUW$VgJW3l/dDUVP/0VnPMETvooErwPXo6vpBL1q1R74MxE=', NULL, false, 'shubhanshu', 'Shubhanshu', 'Tripathi', 'shubhanshu@ornatesolar.com', false, true, '2026-04-30 07:46:43.256293+00', '', 'employee', '', 16, '2026-03-23', 'Ware', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (128, 'pbkdf2_sha256$870000$Ear2aSXv6MBkEMdSSXpGhY$5njtKUg5aUi0RKFf/QshlqM5iV2w/3jjdVjTWOw3zUo=', NULL, false, 'tarun2', 'Tarun', '', 'tarun2@ornatesolar.com', false, true, '2026-04-30 07:46:43.426412+00', '', 'employee', '', 17, '2026-01-01', 'Ornate', 'Kedar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (129, 'pbkdf2_sha256$870000$rpFuksn4ymLeSHRTinrEQf$YvjqMyhWLaXDRz6+TcgcbwmYmsjzeCAS6wUNM9HOdBs=', NULL, false, 'priyank', 'Priyank', 'Rajput', 'priyank@ornatesolar.com', false, true, '2026-04-30 07:46:43.60341+00', '', 'employee', '', 17, '2026-01-01', 'Ornate', 'Kedar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (130, 'pbkdf2_sha256$870000$KjmKMCkBEgYgupju992895$qWx7SILUDQohncyxXsrz7vU4ouNOAxHB6bA5JjvfOy0=', NULL, false, 'anushtha', 'Anushtha', 'Chaudhary', 'anushtha@ornatesolar.com', false, true, '2026-04-30 07:46:43.784386+00', '', 'employee', '', 17, '2026-02-17', 'Ornate', 'Fateh Brar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (131, 'pbkdf2_sha256$870000$2jWZPIfbpOal7GBe5KTZfS$strTKr/44eOPVBtuENQc6Jy+TDAegakQrE6kEYjtkcM=', NULL, false, 'babul', 'Babul', 'Naik', 'babul@ornatesolar.com', false, true, '2026-04-30 07:46:43.964177+00', '', 'employee', 'Technician', 15, '2025-11-19', 'SG Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (132, 'pbkdf2_sha256$870000$9TrrgpYb3L3DOndMDkAzwB$iGxIYuVTW50As0ghCKHCUlzqfRkR2MhOWHaRU2XJGts=', NULL, false, 'anil3', 'Anil', 'Kumar Nair', 'anil3@ornatesolar.com', false, true, '2026-04-30 07:46:44.13226+00', '', 'employee', 'Technician', 15, '2025-06-02', 'SG Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (133, 'pbkdf2_sha256$870000$e2ZdRPOGFTsfNMB9lJRdeH$LbB3rib64bmbI6fpDkBoFfGGvEtWmbW7/irXfa/Ce1M=', NULL, false, 'nabina', 'Nabina', 'Naik', 'nabina@ornatesolar.com', false, true, '2026-04-30 07:46:44.311393+00', '', 'employee', 'Technician', 15, '2025-06-02', 'SG Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (91, 'pbkdf2_sha256$870000$8wu8Fr327fFWmsLmrP7WZT$H3dSfa2DrV0im0ZE7m5zpSAijOdiYx1/PSKzloRyZcM=', NULL, false, 'joel', 'Joel', 'Rajesh', 'joel@ornatesolar.com', false, true, '2026-04-30 07:46:36.649595+00', '', 'employee', '', 20, '2020-09-14', 'Ornate', 'Geetu Bhatija');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (101, 'pbkdf2_sha256$870000$15DctBySQhR55tgBbC2JAH$AUxSbYt3rTdssHGwGzoGf2jNWzBqQOKqMZe5DRgTCFQ=', NULL, false, 'manisha', 'Manisha', '', 'manisha@ornatesolar.com', false, true, '2026-04-30 07:46:38.646249+00', '', 'employee', '', 22, '2025-02-11', 'Ornate', 'Sanjay Shah');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (107, 'pbkdf2_sha256$870000$zPiLGFbtayRLKlm7SkGiku$+Kjw5Q6rXiPgLG3OEFPso7grjLeRpXKiM9Ab9Jp4Q0w=', NULL, false, 'khushi', 'Khushi', 'Chilwal', 'khushi@ornatesolar.com', false, true, '2026-04-30 07:46:39.728569+00', '', 'employee', '', 22, '2025-12-29', 'Rama', 'Sanjay Shah');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (114, 'pbkdf2_sha256$870000$w51AKnd7Yr8Sq0lQn0wYVJ$iHBg3XiSsXrqdd+oAHj3tHTqwW9EVryUBeXbY4yt/Hg=', NULL, false, 'atul', 'Atul', 'Mahajan', 'atul@ornatesolar.com', false, true, '2026-04-30 07:46:40.97918+00', '', 'employee', '', 15, '2025-06-23', 'Rama', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (115, 'pbkdf2_sha256$870000$bTDHNW4yfzQV3gQHKxGBPw$1jfvwup/0E47ix/wVNCkpIhyi21Z9BKmcxITL7EuLrs=', NULL, false, 'chandan', 'Chandan', '', 'chandan@ornatesolar.com', false, true, '2026-04-30 07:46:41.155506+00', '', 'employee', '', 15, '2023-04-23', 'Ware', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (116, 'pbkdf2_sha256$870000$oCUi3VTXPw2KcI1kvSK3wr$xWI9LTZCbKfDn1QeFHZi/qQu0+gsAP79BTjpdXeYYEY=', NULL, false, 'vikas', 'Vikas', 'Kumar', 'vikas@ornatesolar.com', false, true, '2026-04-30 07:46:41.326994+00', '', 'employee', '', 16, '2015-01-01', 'Ornate', 'Tarini Aggarwal');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (117, 'pbkdf2_sha256$870000$8Xs2153KXFf35ZivaOmp6d$Cpon9zzoBw7QNXrnZUQ7sCA0ljVrx7A5rusEX/6nQB0=', NULL, false, 'manmohan', 'Manmohan', '', 'manmohan@ornatesolar.com', false, true, '2026-04-30 07:46:41.502707+00', '', 'employee', '', 16, '2015-04-01', 'Ornate', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (118, 'pbkdf2_sha256$870000$MMIuxTKm3a5HH8IgBbwFWz$KhjMC8+0tXghnEsQeieU6JyTqMTUTbr82QWJ4DJC/jU=', NULL, false, 'nand', 'Nand', 'Lal', 'nand@ornatesolar.com', false, true, '2026-04-30 07:46:41.673728+00', '', 'employee', '', 16, '2025-05-05', 'Ornate', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (119, 'pbkdf2_sha256$870000$Pm5TGgmme2hY7Wd9KifTPc$tCLvi7iUSK7450kPtiDoynhaBf+B2xieAe2oJTltyRU=', NULL, false, 'sanjay2', 'Sanjay', 'Kumar', 'sanjay2@ornatesolar.com', false, true, '2026-04-30 07:46:41.837175+00', '', 'employee', '', 16, '2025-10-06', 'Ornate', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (120, 'pbkdf2_sha256$870000$WTpMSGE15KUNrE35UsIVKW$lh39wGU20EzeOVGb8w1i54vf8ofqm9NJUSQg0enjK04=', NULL, false, 'rajendra', 'Rajendra', 'Bogati', 'rajendra@ornatesolar.com', false, true, '2026-04-30 07:46:42.020077+00', '', 'employee', '', 16, '2026-01-01', 'Ornate', 'Rahul Raj');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (121, 'pbkdf2_sha256$870000$rfNfRE1dVonqDwP2llcgid$wsOQ0z8j157P47aa4S1oWIe69eZqoq9gUK2aXx0BTzg=', NULL, false, 'bijendra', 'Bijendra', 'Ram', 'bijendra@ornatesolar.com', false, true, '2026-04-30 07:46:42.194921+00', '', 'employee', '', 16, '2018-06-14', 'Rama', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (122, 'pbkdf2_sha256$870000$GmcxshytaISZLmGBsvrkrA$ySsfVa8tNKHPv1eZFrCHMyZUfzUwXUjrR6eoWzYueQw=', NULL, false, 'raj', 'Raj', 'Narayan', 'raj@ornatesolar.com', false, true, '2026-04-30 07:46:42.364412+00', '', 'employee', '', 16, '2015-04-01', 'Rama', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (123, 'pbkdf2_sha256$870000$Chl1xthD8Qn5srppuqT4MZ$fR2UmZdi8LdP2zo7kVH39eCiMWJq1t9Vz/ACrPOWhlg=', NULL, false, 'ram', 'Ram', 'Raj Gautam', 'ram@ornatesolar.com', false, true, '2026-04-30 07:46:42.535089+00', '', 'employee', '', 16, NULL, 'Ware', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (124, 'pbkdf2_sha256$870000$isa5BZfiLRxJvsfoXfDb5D$dL9RGQuipcmyhpfEiVx6uJvxv5HN4daGbHPEf8FHKl0=', NULL, false, 'munna', 'Munna', '', 'munna@ornatesolar.com', false, true, '2026-04-30 07:46:42.721251+00', '', 'employee', '', 16, NULL, 'Ware', 'Vikas Kumar');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (134, 'pbkdf2_sha256$870000$c1ggNWTzJESipLkz9z8Uzl$tealR8FqMrFGWD678oImb1SzhkOjZVZvAmHUqvsoO8U=', NULL, false, 'sarfaraz', 'Sarfaraz', 'Alam', 'sarfaraz@ornatesolar.com', false, true, '2026-04-30 07:46:44.485087+00', '', 'employee', 'Site Engineer', 15, '2025-04-22', 'SG Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (135, 'pbkdf2_sha256$870000$IPMkExge9GeBnSJHl01vgH$Q2VSKwE8ktpmA4RePZo4HoRgPQPVYkjWhM8WcC3UmuI=', NULL, false, 'mehzar', 'Mehzar', 'Abbas', 'mehzar@ornatesolar.com', false, true, '2026-04-30 07:46:44.660669+00', '', 'employee', 'Site Engineer', 15, '2025-02-24', 'SG Ornate', 'Arup Hazra');
INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, contact_number, role, title, department_id, date_of_joining, organisation, reporting_manager) VALUES (136, 'pbkdf2_sha256$870000$yDl4JSZ192PKwpXqK4zZgA$oDXy6e6FwvXCqHO/72gZcytsjI/yYN+6QwcfMjrwEsM=', NULL, false, 'ayush', 'Ayush', 'Raj', 'ayush@ornatesolar.com', false, true, '2026-04-30 07:46:44.845574+00', '', 'employee', 'Technician', 15, '2024-09-12', 'SG Ornate', 'Arup Hazra');


--
-- Data for Name: reports_dailyreport; Type: TABLE DATA; Schema: public; Owner: drp_user
--



--
-- Name: departments_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: drp_user
--

SELECT pg_catalog.setval('public.departments_department_id_seq', 23, true);


--
-- Name: reports_dailyreport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: drp_user
--

SELECT pg_catalog.setval('public.reports_dailyreport_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: drp_user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 141, true);


--
-- PostgreSQL database dump complete
--

\unrestrict hmXpjhGfk3grBh6CW8uIZK09r7h1fT7eaUalkwpkIGaUV3KMX2YJTP6FxTSgNEl

